drop table if exists users, requests, items, comments, bookings, status;

create table if not exists users
(
    id bigint generated by default as identity not null,
    user_name varchar not null,
    email varchar not null,
    constraint uq_user_email unique (email),
    constraint pk_user primary key (id)
);

create table if not exists requests
(
    id bigint generated by default as identity not null,
    description varchar not null,
    requester_id bigint references users(id) on delete cascade,
    created timestamp without time zone,
    constraint pk_request primary key (id)
);

create table if not exists items
(
    id bigint generated by default as identity not null,
    name varchar not null,
    description varchar not null,
    available boolean not null,
    owner_id bigint references users(id) on delete cascade not null,
    request_id bigint references requests(id) on delete cascade,
    constraint pk_item primary key (id)
);

create table if not exists comments
(
    id bigint generated by default as identity not null,
    text varchar not null,
    item_id bigint references items(id) on delete cascade not null,
    author_id bigint references users(id) on delete cascade not null,
    created timestamp without time zone,
    constraint pk_comment primary key (id)
);

create table if not exists bookings
(
    id bigint generated by default as identity not null,
    start_date timestamp without time zone not null,
    end_date timestamp without time zone not null,
    item_id bigint references items(id) on delete cascade not null,
    booker_id bigint references users(id) on delete cascade not null,
    status varchar,
    constraint pk_booking primary key (id)
);

create table if not exists status
(
    id bigint generated by default as identity primary key,
    name varchar unique
);